services:
  mysql_db:
    image: mysql:8.0
    container_name: rhdp_mysql_local
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: data23
      MYSQL_DATABASE: database
      MYSQL_USER: data
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306" # Map host port 3307 to container port 3306
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local

