<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Désactiver tous les membres actuels du directoire sauf le président Alassane Ouattara
        DB::table('organization_structure')
            ->where('group', 'directoire')
            ->where('name', '!=', 'SEM Alassane Ouattara')
            ->update(['is_active' => false]);

        // Mise à jour des membres du directoire selon la nouvelle liste
        $directoireMembers = [
            // Conserver le président Alassane Ouattara (ne pas modifier)
            // [
            //     'name' => 'SEM Alassane Ouattara',
            //     'title' => 'Président du RHDP',
            //     'image' => 'images/membres/Alassane_Outtara.png',
            //     'role' => 'president',
            //     'group' => 'directoire',
            //     'order' => 1,
            // ],
            
            // Nouveaux membres selon la liste fournie
            [
                'name' => 'M. Gilbert Koné KAFANA',
                'title' => 'Président',
                'region' => 'Poro',
                'contact' => '07 07 87 73 03',
                'role' => 'president_directoire',
                'group' => 'directoire',
                'order' => 2,
                'is_active' => true,
            ],
            [
                'name' => 'M. Robert BEUGRE MAMBE',
                'title' => 'Vice-Président',
                'region' => 'Grands Ponts',
                'contact' => '01 01 87 87 00',
                'role' => 'vice_president',
                'group' => 'directoire',
                'order' => 3,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Kandia CAMARA',
                'title' => 'Vice-Présidente',
                'region' => 'Kabadougou',
                'contact' => '01 01 07 07 77',
                'role' => 'vice_president',
                'group' => 'directoire',
                'order' => 4,
                'is_active' => true,
            ],
            [
                'name' => 'M. TENE Birahima OUATTARA',
                'title' => 'Trésorier Général',
                'region' => 'Tchologo',
                'contact' => '05 05 07 07 77',
                'role' => 'tresorier',
                'group' => 'directoire',
                'order' => 5,
                'is_active' => true,
            ],
            [
                'name' => 'M. Kobenan ADJOUMANI',
                'title' => 'Porte-Parole Principal',
                'region' => 'Moronou',
                'contact' => '07 07 07 07 10',
                'role' => 'porte_parole',
                'group' => 'directoire',
                'order' => 6,
                'is_active' => true,
            ],
            [
                'name' => 'M. Abdallah Toikeusse MABRI',
                'title' => 'Vice-Président',
                'region' => 'Tonpki',
                'contact' => '07 07 89 52 34',
                'role' => 'vice_president',
                'group' => 'directoire',
                'order' => 7,
                'is_active' => true,
            ],
            [
                'name' => 'M. Bacongo CISSE',
                'title' => 'Secrétaire Exécutif',
                'region' => 'Bagoué',
                'contact' => '07 07 09 09 10',
                'role' => 'secretaire_executif',
                'group' => 'directoire',
                'order' => 8,
                'is_active' => true,
            ],
            [
                'name' => 'M. Fidèle SARASSORO',
                'title' => 'Membre',
                'region' => 'Poro',
                'contact' => '07 09 44 16 93',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 9,
                'is_active' => true,
            ],
            [
                'name' => 'M. Ally COULIBALY',
                'title' => 'Membre',
                'region' => 'Bagoué',
                'contact' => '07 08 63 53 71',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 10,
                'is_active' => true,
            ],
            [
                'name' => 'M. Mamadou SANGAFOWA',
                'title' => 'Membre',
                'region' => 'Folon',
                'contact' => '07 07 31 11 11',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 11,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Nialé KABA',
                'title' => 'Membre',
                'region' => 'Bagoué',
                'contact' => '01 01 58 58 22',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 12,
                'is_active' => true,
            ],
            [
                'name' => 'M. Souleymane DIARRASSOUBA',
                'title' => 'Membre',
                'region' => 'Haut-Sassandra',
                'contact' => '07 07 07 07 07',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 13,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Anne Désirée OULOTO',
                'title' => 'Membre',
                'region' => 'Cavally',
                'contact' => '07 07 78 78 03',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 14,
                'is_active' => true,
            ],
            [
                'name' => 'M. Amadou KONE',
                'title' => 'Membre',
                'region' => 'Béré',
                'contact' => '07 87 21 21 21',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 15,
                'is_active' => true,
            ],
            [
                'name' => 'M. Adama COULIBALY',
                'title' => 'Membre',
                'region' => 'N\'zi',
                'contact' => '07 48 31 40 40',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 16,
                'is_active' => true,
            ],
            [
                'name' => 'M. Bruno Nabagné KONE',
                'title' => 'Membre',
                'region' => 'Hambol',
                'contact' => '07 07 15 80 90',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 17,
                'is_active' => true,
            ],
            [
                'name' => 'M. Maurice BANDAMA',
                'title' => 'Membre',
                'region' => 'BAFING',
                'contact' => '07 09 83 38 37',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 18,
                'is_active' => true,
            ],
            [
                'name' => 'M. Laurent TCHAGBA',
                'title' => 'Membre',
                'region' => 'Guémon',
                'contact' => '07 07 07 07 08',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 19,
                'is_active' => true,
            ],
            [
                'name' => 'M. Siandou FOFANA',
                'title' => 'Membre',
                'region' => 'San-Pedro',
                'contact' => '07 07 07 07 09',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 20,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Mariatou KONE',
                'title' => 'Membre',
                'region' => 'Bélier',
                'contact' => '07 07 92 21 90',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 21,
                'is_active' => true,
            ],
            [
                'name' => 'M. Souleymane DIARRASSOUBA',
                'title' => 'Membre',
                'region' => 'Indénié-Djuablin',
                'contact' => '07 07 07 07 07',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 22,
                'is_active' => true,
            ],
            [
                'name' => 'M. Paulin DANHO',
                'title' => 'Membre',
                'region' => 'Iffou',
                'contact' => '07 07 92 92 20',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 23,
                'is_active' => true,
            ],
            [
                'name' => 'M. Sidi Tiémoko TOURE',
                'title' => 'Membre',
                'region' => 'Gbêkê',
                'contact' => '07 09 09 02 21',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 24,
                'is_active' => true,
            ],
            [
                'name' => 'M. Amadou COULIBALY',
                'title' => 'Membre',
                'region' => 'Poro',
                'contact' => '07 07 92 92 20',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 25,
                'is_active' => true,
            ],
            [
                'name' => 'M. Mamadou TOURE',
                'title' => 'Porte-Parole Adjoint',
                'region' => 'Sud-Comoé',
                'contact' => '05 05 14 16 15',
                'role' => 'porte_parole_adjoint',
                'group' => 'directoire',
                'order' => 26,
                'is_active' => true,
            ],
            [
                'name' => 'M. Adama BICTOGO',
                'title' => 'Membre',
                'region' => 'Gontougo',
                'contact' => '07 07 07 07 07',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 27,
                'is_active' => true,
            ],
            [
                'name' => 'M. Adama DIAWARA',
                'title' => 'Membre',
                'region' => 'Tchologo',
                'contact' => '05 05 01 68 02',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 28,
                'is_active' => true,
            ],
            [
                'name' => 'M. Pierre DIMBA',
                'title' => 'Membre',
                'region' => 'Agnéby-Tiassa',
                'contact' => '05 05 28 68 08',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 29,
                'is_active' => true,
            ],
            [
                'name' => 'M. Bouaké FOFANA',
                'title' => 'Membre',
                'region' => 'Worodougou',
                'contact' => '07 07 52 04 04',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 30,
                'is_active' => true,
            ],
            [
                'name' => 'M. Sansan KAMBILE',
                'title' => 'Membre',
                'region' => 'Tonkpi',
                'contact' => '07 07 53 63 03',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 31,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Myss Belmonde DOGO',
                'title' => 'Membre',
                'region' => 'Gôh',
                'contact' => '07 07 49 92 51',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 32,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Nassénéba TOURE',
                'title' => 'Membre',
                'region' => 'Kabadougou',
                'contact' => '07 07 49 92 51',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 33,
                'is_active' => true,
            ],
            [
                'name' => 'M. Amedé KOUAKOU',
                'title' => 'Membre',
                'region' => 'Lôh-Djiboua',
                'contact' => '07 07 92 92 20',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 34,
                'is_active' => true,
            ],
            [
                'name' => 'M. Vagondo DIOMANDE',
                'title' => 'Membre',
                'region' => 'BOUNKANI',
                'contact' => '07 07 07 07 07',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 35,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Anne OULOTO',
                'title' => 'Membre',
                'region' => 'Cavally',
                'contact' => '07 07 78 78 03',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 36,
                'is_active' => true,
            ],
            [
                'name' => 'M. Félix ANOBLE',
                'title' => 'Membre',
                'region' => 'San-Pedro',
                'contact' => '07 07 12 09 07',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 37,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Jeanne Patricia AYAI',
                'title' => 'Membre',
                'region' => 'Lôh-Djiboua',
                'contact' => '07 09 57 05 51',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 38,
                'is_active' => true,
            ],
            [
                'name' => 'M. N\'ZI MIAN',
                'title' => 'Membre',
                'region' => 'Tonkpi',
                'contact' => '07 09 52 52 06',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 39,
                'is_active' => true,
            ],
            [
                'name' => 'M. Jean Narcisse GOMINA',
                'title' => 'Membre',
                'region' => 'Nawa',
                'contact' => '07 07 59 59 92',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 40,
                'is_active' => true,
            ],
            [
                'name' => 'M. Mamadou TOURE',
                'title' => 'Membre',
                'region' => 'Gbôklé',
                'contact' => '07 07 34 77 33',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 41,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Raymonde GOUDOU',
                'title' => 'Membre',
                'region' => 'Bélier',
                'contact' => '07 07 94 45 51',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 42,
                'is_active' => true,
            ],
            [
                'name' => 'M. Souleymane DIARASSOUBA',
                'title' => 'Membre',
                'region' => 'Bafing',
                'contact' => '07 07 42 42 41',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 43,
                'is_active' => true,
            ],
            [
                'name' => 'M. Léon Emmanuel MONNET',
                'title' => 'Membre',
                'region' => 'Grands-Ponts',
                'contact' => '07 48 59 26 26',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 44,
                'is_active' => true,
            ],
            [
                'name' => 'KOUA ALEM METCH',
                'title' => 'Membre',
                'region' => 'Grands-Ponts',
                'contact' => '07 48 59 26 26',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 45,
                'is_active' => true,
            ],
            [
                'name' => 'M. Félix ANOBLE',
                'title' => 'Chargé de la stratégie électorale',
                'region' => 'San-Pedro',
                'contact' => '07 07 12 09 07',
                'role' => 'charge_mission',
                'group' => 'directoire',
                'order' => 46,
                'is_active' => true,
            ],
            [
                'name' => 'Mme Jeanne Patricia AYAI',
                'title' => 'Chargé de l\'administration et de l\'organisation du parti',
                'region' => 'Lôh-Djiboua',
                'contact' => '07 07 14 47 47',
                'role' => 'charge_mission',
                'group' => 'directoire',
                'order' => 47,
                'is_active' => true,
            ],
            [
                'name' => 'M. Adama COULIBALY',
                'title' => 'Chargé de l\'administration et de l\'organisation du parti',
                'region' => 'Poro',
                'contact' => '07 08 61 13 33',
                'role' => 'charge_mission',
                'group' => 'directoire',
                'order' => 48,
                'is_active' => true,
            ],
            [
                'name' => 'M. Ally COULIBALY',
                'title' => 'Chargé de l\'administration et de l\'organisation du parti',
                'region' => 'Poro',
                'contact' => '01 58 83 02 00',
                'role' => 'charge_mission',
                'group' => 'directoire',
                'order' => 49,
                'is_active' => true,
            ],
            [
                'name' => 'M. Aboubacar Karamoko FOFANA',
                'title' => 'Chargé de l\'administration et de l\'organisation du parti',
                'region' => 'Bafing',
                'contact' => '07 07 18 18 01',
                'role' => 'charge_mission',
                'group' => 'directoire',
                'order' => 50,
                'is_active' => true,
            ],
            [
                'name' => 'KOUA ALEM METCH',
                'title' => 'Membre',
                'region' => 'Grands-Ponts',
                'contact' => '07 48 59 26 26',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 51,
                'is_active' => true,
            ],
            [
                'name' => 'JOSEPH SEKA SEKA',
                'title' => 'Membre',
                'region' => 'La ME',
                'contact' => null,
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 52,
                'is_active' => true,
            ],
            [
                'name' => 'KONATE SIDIMORY KAOU',
                'title' => 'Membre',
                'region' => null,
                'contact' => '07 47 31 31 90',
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 53,
                'is_active' => true,
            ],
            [
                'name' => 'IBRAHIMA OUATTARA',
                'title' => 'Membre',
                'region' => 'Tchologo',
                'contact' => null,
                'role' => 'membre',
                'group' => 'directoire',
                'order' => 54,
                'is_active' => true,
            ],
        ];

        // Insérer ou mettre à jour les membres du directoire
        foreach ($directoireMembers as $member) {
            // Vérifier si le membre existe déjà
            $existingMember = DB::table('organization_structure')
                ->where('name', $member['name'])
                ->where('group', 'directoire')
                ->first();
            
            if ($existingMember) {
                // Mettre à jour le membre existant
                DB::table('organization_structure')
                    ->where('id', $existingMember->id)
                    ->update([
                        'title' => $member['title'],
                        'role' => $member['role'],
                        'order' => $member['order'],
                        'is_active' => true,
                        'updated_at' => now(),
                    ]);
            } else {
                // Insérer un nouveau membre
                DB::table('organization_structure')->insert([
                    'name' => $member['name'],
                    'title' => $member['title'],
                    'role' => $member['role'],
                    'group' => 'directoire',
                    'order' => $member['order'],
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]);
            }
        }
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Restaurer les membres du directoire à leur état initial
        $defaultMembers = [
            [
                'name' => 'SEM Alassane Ouattara',
                'title' => 'Président du RHDP',
                'image' => 'images/membres/Alassane_Outtara.png',
                'role' => 'president',
                'group' => 'directoire',
                'order' => 1,
            ],
            [
                'name' => 'M. Robert Beugré Mambé',
                'title' => 'Vice-Président',
                'image' => 'images/membres/directoire/beugre.webp',
                'role' => 'vice_president',
                'group' => 'directoire',
                'order' => 2,
            ],
            [
                'name' => 'Mme Kandia Camara',
                'title' => 'Vice-Présidente',
                'image' => 'images/membres/directoire/kandia-camara.jpg',
                'role' => 'vice_president',
                'group' => 'directoire',
                'order' => 3,
            ],
            [
                'name' => 'M. Abdallah Toikeusse Mabri',
                'title' => 'Vice-Président',
                'image' => 'images/membres/directoire/M. ABDALLAH TOIKEUSSE MABRI.jpg',
                'role' => 'vice_president',
                'group' => 'directoire',
                'order' => 4,
            ],
            [
                'name' => 'M. Tene Birahima Ouattara',
                'title' => 'Trésorier Général',
                'image' => 'images/membres/directoire/Tene-Brahima-Ouattara.jpeg',
                'role' => 'tresorier',
                'group' => 'directoire',
                'order' => 5,
            ],
            [
                'name' => 'M. Kouassi Kobenan Adjoumani',
                'title' => 'Porte-Parole Principal',
                'image' => 'images/membres/directoire/Kobenan_Kouassi_Adjoumani.jpg',
                'role' => 'porte_parole',
                'group' => 'directoire',
                'order' => 6,
            ],
            [
                'name' => 'M. Mamadou Touré',
                'title' => 'Porte-Parole Adjoint',
                'image' => 'images/membres/directoire/mamadou-toure.jpg',
                'role' => 'porte_parole_adjoint',
                'group' => 'directoire',
                'order' => 7,
            ],
            [
                'name' => 'M. Bacongo Ibrahima Cisse',
                'title' => 'Secrétaire Exécutif',
                'image' => 'images/membres/directoire/cisse-bacongo.webp',
                'role' => 'secretaire_executif',
                'group' => 'directoire',
                'order' => 8,
            ],
            [
                'name' => 'M. Félix Anoblé',
                'title' => 'Chargé de la Stratégie Électorale',
                'image' => 'images/membres/directoire/felix-anoble.jpg',
                'role' => 'charge_mission',
                'group' => 'directoire',
                'order' => 9,
            ],
        ];

        // Supprimer tous les membres du directoire
        DB::table('organization_structure')
            ->where('group', 'directoire')
            ->delete();

        // Réinsérer les membres par défaut
        foreach ($defaultMembers as $member) {
            DB::table('organization_structure')->insert(array_merge($member, [
                'created_at' => now(),
                'updated_at' => now(),
                'is_active' => true,
            ]));
        }
    }
};
